[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
[project]
name = "stroll-1-py"
version = "0.1.1"
authors = [
    {name = "Huberkeep", email = "HuberkeepInGithub@hotmail.com"}
]
description = "A brief description of your package"
readme = "README.md"
